name: Tianon's Ramblings ✿
permalink: /post/:year/:month/:day/:title.html

markdown: kramdown

# let me use future dates as lazy drafts :)
future: false

# let's be explicit
encoding: utf-8
timezone: America/Los_Angeles

# some useful values within the site
author: Tianon Gravi
email: admwiggin@gmail.com
uri: https://tianon.xyz

# stuff github-pages overrides anyhow, so let's be consistent
# see also https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
lsi: false
highlighter: rouge
safe: true
