name: Tianon's Ramblings
markdown: redcarpet
permalink: /post/:year/:month/:day/:title.html

author: Tianon Gravi
email: admwiggin@gmail.com
uri: http://tianon.github.io

# stuff github-pages overrides anyhow, so let's be consistent
# see also https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
lsi: false
pygments: true
safe: true
